### ISSUE TITLE
Referenced track not found

### ISSUE THREAD

**Issue by shillshocked** [naueramant/Audiblex#1]
After 62 chapters, I get:

Referenced QT chapter track not found

Stops processing m4bs correctly at that point.

Also the m4a cuts off at around 6 hours.

**Comment by naueramant** [comment]
That error is from the file converter. Take a look here [jostyee/AAXtoM4B ]( https://github.com/jostyee/AAXtoM4B ).

Since i'm not maintaining the converters i will close this issue and recommend that you open it on jostyee's repo.

**Comment by naueramant** [comment]
It could however been nice to be independent from the converter binaries and just use ffmpeg. If you want to give it at shot and implement it, that would be much appreciated.
